### ISSUE TITLE
Could you help please with AlexeyAB / darknet

### ISSUE THREAD

**Issue by Vladimir-v1** [hankerkuo/Vehicle-Front-Rear-Detection-for-License-Plate-Detection-Enhancement#6]
Hello!
First, thank you so much for your work and this solution!
I'm trying to use TensorRT version of darknet on Jetson Xavier, instead of https://github.com/pjreddie/darknet,
but getting NULL Pointer error. Could you please explain and give advice if it possible to resolve this issue

Thank you so much in advance!

root@jetsonNX:/home/user/Vehicle-Front-Rear-Detection-for-License-Plate-Detection-Enhancement# python Front_Rear_Detect.py
FRD Net pre-loading...
 Try to load cfg: data/FRD/FRNet_YOLOv3_tiny.cfg, clear = 0
 0 : compute_capability = 720, cudnn_half = 1, GPU: Xavier
net.optimized_memory = 0
mini_batch = 1, batch = 1, time_steps = 1, train = 1
   layer   filters  size/strd(dil)      input                output
   0 Create CUDA-stream - 0
 Create cudnn-handle 0
conv     16       3 x 3/ 1    416 x 416 x   3 ->  416 x 416 x  16 0.150 BF
   1 max                2x 2/ 2    416 x 416 x  16 ->  208 x 208 x  16 0.003 BF
   2 conv     32       3 x 3/ 1    208 x 208 x  16 ->  208 x 208 x  32 0.399 BF
   3 max                2x 2/ 2    208 x 208 x  32 ->  104 x 104 x  32 0.001 BF
   4 conv     64       3 x 3/ 1    104 x 104 x  32 ->  104 x 104 x  64 0.399 BF
   5 max                2x 2/ 2    104 x 104 x  64 ->   52 x  52 x  64 0.001 BF
   6 conv    128       3 x 3/ 1     52 x  52 x  64 ->   52 x  52 x 128 0.399 BF
   7 max                2x 2/ 2     52 x  52 x 128 ->   26 x  26 x 128 0.000 BF
   8 conv    256       3 x 3/ 1     26 x  26 x 128 ->   26 x  26 x 256 0.399 BF
   9 max                2x 2/ 2     26 x  26 x 256 ->   13 x  13 x 256 0.000 BF
  10 conv    512       3 x 3/ 1     13 x  13 x 256 ->   13 x  13 x 512 0.399 BF
  11 max                2x 2/ 1     13 x  13 x 512 ->   13 x  13 x 512 0.000 BF
  12 conv   1024       3 x 3/ 1     13 x  13 x 512 ->   13 x  13 x1024 1.595 BF
  13 conv    256       1 x 1/ 1     13 x  13 x1024 ->   13 x  13 x 256 0.089 BF
  14 conv    512       3 x 3/ 1     13 x  13 x 256 ->   13 x  13 x 512 0.399 BF
  15 conv     21       1 x 1/ 1     13 x  13 x 512 ->   13 x  13 x  21 0.004 BF
  16 yolo
[yolo] params: iou loss: mse (2), iou_norm: 0.75, obj_norm: 1.00, cls_norm: 1.00, delta_norm: 1.00, scale_x_y: 1.00
  17 route  13                                     ->   13 x  13 x 256
  18 conv    128       1 x 1/ 1     13 x  13 x 256 ->   13 x  13 x 128 0.011 BF
  19 upsample                 2x    13 x  13 x 128 ->   26 x  26 x 128
  20 route  19 8                                   ->   26 x  26 x 384
  21 conv    256       3 x 3/ 1     26 x  26 x 384 ->   26 x  26 x 256 1.196 BF
  22 conv     21       1 x 1/ 1     26 x  26 x 256 ->   26 x  26 x  21 0.007 BF
  23 yolo
[yolo] params: iou loss: mse (2), iou_norm: 0.75, obj_norm: 1.00, cls_norm: 1.00, delta_norm: 1.00, scale_x_y: 1.00
Total BFLOPS 5.449
avg_outputs = 325057
 Allocate additional workspace_size = 38.79 MB
 Try to load weights: data/FRD/FRNet_YOLOv3_tiny_126000.weights
Loading weights from data/FRD/FRNet_YOLOv3_tiny_126000.weights...
 seen 64, trained: 8064 K-images (126 Kilo-batches_64)
Done! Loaded 24 layers from weights-file
Loaded - names_list: data/FRD/FRNet.names, classes = 2
2021-06-17 22:57:35.861504
('\t\t\tdetecting front and rear using FRD..., Model:', 'data/FRD/FRNet_YOLOv3_tiny.cfg')
Traceback (most recent call last):
  File "Front_Rear_Detect.py", line 68, in <module>
    FRs, cate = fr_detect(img, start)
  File "Front_Rear_Detect.py", line 32, in fr_detect
    results, wh = dn.detect(FR_net, FR_meta, img, threshold)
  File "/home/user/Vehicle-Front-Rear-Detection-for-License-Plate-Detection-Enhancement/darknet/python/darknet.py", line 160, in detect
    if dets[j].prob[i] > 0:
ValueError: NULL pointer access

**Comment by Vladimir-v1** [comment]
just for information, if set GPU=1 and cuDNN=0 everything working very fast(preloading and image processing), processing of image is 0.4 second instead 8 seconds if cuDNN is 1. Maybe this information can help to somebody too
